{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lhs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lhs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lhs/lhs_{{ version }}.tar.gz
  sha256: 6b4b773c6b322f1ffb3e2ef49c244ec8a3958a0346a1cc8f42f0d0951e8b0724

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp

test:
  commands:
    - $R -e "library('lhs')"           # [not win]
    - "\"%R%\" -e \"library('lhs')\""  # [win]

about:
  home: https://github.com/bertcarnell/lhs
  license: GPL-3.0-only
  summary: Provides a number of methods for creating and augmenting Latin Hypercube Samples.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: lhs
# Title: Latin Hypercube Samples
# Version: 1.0.1
# Authors@R:  person(given = "Rob", family = "Carnell", role = c("aut", "cre"), email = "bertcarnell@gmail.com")
# Description: Provides a number of methods for creating and augmenting Latin Hypercube Samples.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.4.0)
# LinkingTo: Rcpp
# Imports: Rcpp
# Suggests: testthat, DoE.base, knitr, rmarkdown, covr
# URL: https://github.com/bertcarnell/lhs
# BugReports: https://github.com/bertcarnell/lhs/issues
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2019-02-02 20:54:26 UTC; bertc
# Author: Rob Carnell [aut, cre]
# Maintainer: Rob Carnell <bertcarnell@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-02-03 11:00:14 UTC
