appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Yer43mX0k/pCYp8lObDpsR8PpC63/0ECi3JkYVbmQx2ycWm7yVFecPwv78kz9e+H8t12kiiJjYsv7MSp3kU+Z9lNh3mslSPlIr7fzPF1og8z9IVz8up21X7ecai2KB8O0LntzoYLP2Ac5UEACWCZ/iLGQWfnwPuYKrdoo3FP1TudzTo90zrKofYkyolokHj9knNWoxubBjsdFUTPyr3IJdFU4b/vIXiQVjBrDH1AB75FaM/ZDW3bx0VpHAt3ckTnXX3J+RukFyITDKf6mK3apeEgjxk3Q5KSDmrCgYom+4ESQhR18yum6gvLnFNJXOzcsIuGKPqhPW3nUvmg1w9Qd0BA5dWJECzpAh5BAXqgV2iQjFgzdFZ915rnlH6yl0RI5CdFl7jgITMbxuTeBj3t+ZI3hwQUXCG8+KCO3OEnvWMt66YAvUbYspVqpo+8lbJzDwVvTjCDN1E7XkeG811O+auXX6wPNJ5BHekG9MvikmDulKhbBqF4FZ+82CnOH+0LT3iGW/utSIKEKDKorYShUdH48JexSAtLnNozSOU+vI7Kn6GbjsrFJkUd0MWtPdeEXo0QNeGr2c/ULYj0pt/vhJKcBysBPnxzJ8E++JO+aFN3496XLfvfxX5QTynpLuV7CnvjS7OTwKpU7NB8b0gVGMTWnQ4QYO7Ocj2s/o7lC0s=}
