travis:
  secure:
    BINSTAR_TOKEN: I7drTGXYCGlc6APo+a+sSGrkQQ+3FWawas5gFXX69/AVPWA0G77jw8qXYPL68bMmAIMmAKsarcw0of56G34u0AsIkV+LRLXEK6KFoOs1ki0CsLwWlctjJErV4ENzmb8aPlrvLzeMH6Lm5LSy2rFM8PHyc/pSUlP2gmJbEQtmIAMPnQ980g6IFLH/Hz85wGV4P2jFA/Ku3ZvmlQOYYxhSh04lVKrlov2DC4WsEOawF4xn5j9wqk9zC05O06HgAnsx4ac45P/R2GK7YMF7qxgPq91xvm3yqQY9V3M/C5kOVrdrm0zUBYm5EcSZl1qe0Mn075+4+DOda/rbSMtlgl37PU8LLIcBb7HrtmMi+wrqOnFtt6nBzsWRJ0PHrG9QqKRKGbANsrD2J68uxhv7J8P9Vu4vKOuIIfUflmD+MMKp9sLjrYW1twc3N9JIE+iET87YCWfFVhMN4kkfekkSVpEajsPstsajEzBRp+BMzJck6ZIsTGlBRWjcE2CF7ZbrB55Px7C6BAmJvtQPCuvUJ6LUxaaXNNZ5qMfnvQd47tlgQzT2Cst+yiuo/lNPlowA2XY2c1PJTKMoYQFKD1DsVJfUjan3nSwXRp2vV8LpbrmLYOLT69Noi+9w3VKiTnidt5qIx8HLTVqz+P27meK6WuVxvTi7bzMl9BFeoSWUO3p+uxc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
